# ERL-1328 - Deprecated catch

## Example

```erlang
%% foo.erl
-module(foo).
-export([t/1]).
-compile(warn_deprecated_catch).
t(X) -> catch [ L || L <- X].
```

```
$ erlc foo.erl
foo.erl:4:9: Warning: 'catch ...' is deprecated and will be removed in a
future version of Erlang/OTP; please use 'try ... catch ... end' instead.
Compile directive 'nowarn_deprecated_catch' can be used to suppress
warnings in selected modules.
%    4| t(X) -> catch [ L || L <- X].
%     |         ^
% help: call `erlc -explain ERL-1328` to see a detailed explanation
```

## Explanation

This warning is generated by the Erlang linter for all `catch` expressions
without a `try`. Erlang's old-style `catch` can be used to catch the exception
thrown by the following expression. It is now deprecated and gradually
being replaced by the newer `try/catch`. For now, this warning is not raised
by default. It is raised only when the compile option `warn_deprecated_catch`
is enabled.

To fix this warning, refactor the usage of `catch` to be a `try/catch`
construct. One way to refactor the example above is the following:

```erlang
t(X) ->
    try [ L || L <- X] of
        Value -> Value
    catch
        throw:Reason -> Reason
    end.
```

If the `catch` expression is intended to match a specific error, an easy
way to refactor is to include this library: `-include_lib("stdlib/include/assert.hrl").`.
It contains various assert macros that can replace the use of `catch`
expressions.
